# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [1]:
# Your code here
import pandas as pd
url="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"

df=pd.read_csv(url)
print(df.columns)
df=df.rename(columns={'ST': 'state'})

df.columns=[col.lower().replace(" ","_") for col in df.columns]
print(df.columns)

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')
Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [2]:
# Gender standarization
gender={'Femal':'F', 'Male':'M', 'female':'F'}
df.gender=df.gender.map(gender)
df.gender.unique()

array([nan, 'F', 'M'], dtype=object)

In [3]:
#State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", 
#"WA": "Washington"

df.state=df.state.replace({'AZ':'Arizona', 'WA':'Washington','Cali':'California'})
df.state.unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [4]:
#In education, "Bachelors" could be replaced by "Bachelor"
df.education= df.education.replace('Bachelors','Bachelor')
df.education.unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [5]:
#In Customer Lifetime Value, delete the % character
df['customer_lifetime_value']=df['customer_lifetime_value'].str.replace('%','',regex=False)

In [6]:
#In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by 
#"Luxury"

df.vehicle_class= df.vehicle_class.replace({
    "Sports Car": 'Luxury',
    "Luxury SUV": 'Luxury',
    "Luxury Car": 'Luxury'})

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [7]:
df.head(2)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,NaN,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     84 non-null     object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   object
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [9]:
# Customer lifetime value should be numeric
df.customer_lifetime_value=df.customer_lifetime_value.astype(float)

df.customer_lifetime_value=pd.to_numeric(df.customer_lifetime_value)
df.customer_lifetime_value.dtype

dtype('float64')

In [10]:
#Number of open complaints has an incorrect format. Look at the different values it takes 
#with unique() and take the middle value. As an example, 1/5/00 should be 5. Number of open 
#complaints is a string - remember you can use split() to deal with it and take the number you 
#need. Finally, since it should be numeric, cast the column to be in its proper type.
df.head()
df.number_of_open_complaints=df.number_of_open_complaints.str.split('/').map(lambda x: x[1] if isinstance(x,list) else x )

In [11]:
df.number_of_open_complaints=pd.to_numeric(df.number_of_open_complaints)
df.number_of_open_complaints.dtype

dtype('float64')

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [12]:
#use the isnull() function in pandas to find columns with null values.
display(df.isnull().sum())

customer                     2937
state                        2937
gender                       3924
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [13]:
#Decide on a strategy for handling the null values.
#number of nulls per column
display(df.head(2))
display(df.info())

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,NaN,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     84 non-null     object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 344.6+ KB

None

In [14]:
#Drop the rows for which all columns have null values
df=df.dropna(how='all')

In [15]:
df.isnull().sum()

customer                       0
state                          0
gender                       987
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [16]:
#left columns with nulss are gender and customer life time value.
#fill gender with mode
df.gender=df.gender.fillna(df.gender.mode()[0])

#fill customer_lifetime_value

df.customer_lifetime_value=df.customer_lifetime_value.fillna(round(df.customer_lifetime_value.mean()))
#Verify that your strategy has successfully handled the null values. You can use the isnull() function again to check if there are still null values in the dataset.
df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [18]:
# Checking if there are duplicates
df.duplicated().sum()
df.duplicated()
#there are no duplicates.

0       False
1       False
2       False
3       False
4       False
        ...
1066    False
1067    False
1068    False
1069    False
1070    False
Length: 1071, dtype: bool

In [19]:
df.info()
col_numeric= df.select_dtypes(include='number').columns
#to convert to int there must be non null values
df[col_numeric].isnull().sum()
# we round the columns with decimals
df[col_numeric]=df[col_numeric].applymap(lambda x: round(x) if isinstance(x,float) else x)

# we check if there are columns with decimals or not
df[col_numeric].apply(lambda x: (x%1==0).all)

df[col_numeric].apply(lambda x: x.astype(int) for x in col_numeric)

<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     1071 non-null   object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1071 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 100.4+ KB

/var/folders/y7/p6n8z7nn4fs88vn9n57nxbh40000gn/T/ipykernel_15298/2954220657.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[col_numeric]=df[col_numeric].applymap(lambda x: round(x) if isinstance(x,float) else x)

ValueError: No objects to concatenate

In [21]:
#exporting to csv
df.to_csv('labday2.csv', index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here